[package]
name = "aart"
version = "0.1.0"
edition = "2021"
description = "An ASCII art generator."
license = "Unlicense"

[dependencies]
clap = {version = "4.5.20", features = ["derive"]}
image = "0.25.4"
